apiVersion: v1
data:
  tls.crt: Y2VydA== # replace with Certificate (fullchain - certificate - intermediate cert - root cert ) for frontend domain base64 encoded
  tls.key: cHJpdmF0ZSBrZXkg # replace with Private key for above certificate base64 encoded
kind: Secret
metadata:
  name: backend
type: kubernetes.io/tls